version: '3.4'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'electron-filer'
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      DISPLAY: host.docker.internal:0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
